DROP TABLE IF EXISTS playlists;
CREATE TABLE playlists(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(50) NOT NULL,
	url TEXT NOT NULL,
	downloaded_tracks INTEGER
);


DROP TABLE IF EXISTS tracks;
CREATE TABLE tracks(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	playlist_id INTEGER,
	download_id INTEGER NOT NULL,
	FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON UPDATE CASCADE ON DELETE CASCADE
);
