DROP TABLE IF EXISTS playlists;
CREATE TABLE playlists(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(50) NOT NULL,
	url TEXT NOT NULL,
	total_tracks INTEGER,
	downloaded_tracks INTEGER,
	pending_tracks INTEGER,
	status VARCHAR(10) CHECK (status IN ('DOWNLOADED','DOWNLOADING','FAILED','UNTOUCHED'))
);

DROP TABLE IF EXISTS tracks;
CREATE TABLE tracks(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	playlist_id INTEGER,
	status VARCHAR(10) CHECK (status IN ('DOWNLOADED','DOWNLOADING','FAILED','UNTOUCHED')),
	FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON UPDATE CASCADE ON DELETE CASCADE
);
